// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOcSsle1z95tAwpRxUvt94zxH3veilu0I',
    appId: '1:654664809716:web:c1d9169fd000f653ccf2a1',
    messagingSenderId: '654664809716',
    projectId: 'toranomon-civictech',
    authDomain: 'toranomon-civictech.firebaseapp.com',
    storageBucket: 'toranomon-civictech.firebasestorage.app',
    measurementId: 'G-0JPH234J4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-N_xe_FJ5jgy0-owXTeEtRnVOPA7OV1w',
    appId: '1:654664809716:android:2faa90397f0909fcccf2a1',
    messagingSenderId: '654664809716',
    projectId: 'toranomon-civictech',
    storageBucket: 'toranomon-civictech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyltMHCO1g5EdbVza5vAmsRVa5k7GR_r8',
    appId: '1:654664809716:ios:c704d926745f1507ccf2a1',
    messagingSenderId: '654664809716',
    projectId: 'toranomon-civictech',
    storageBucket: 'toranomon-civictech.firebasestorage.app',
    iosClientId: '654664809716-i9cqpvlag7a4desr93fe9t0tsgmhs8so.apps.googleusercontent.com',
    iosBundleId: 'com.example.toranomonCivictech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyltMHCO1g5EdbVza5vAmsRVa5k7GR_r8',
    appId: '1:654664809716:ios:c704d926745f1507ccf2a1',
    messagingSenderId: '654664809716',
    projectId: 'toranomon-civictech',
    storageBucket: 'toranomon-civictech.firebasestorage.app',
    iosClientId: '654664809716-i9cqpvlag7a4desr93fe9t0tsgmhs8so.apps.googleusercontent.com',
    iosBundleId: 'com.example.toranomonCivictech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOcSsle1z95tAwpRxUvt94zxH3veilu0I',
    appId: '1:654664809716:web:d8df81c98199f178ccf2a1',
    messagingSenderId: '654664809716',
    projectId: 'toranomon-civictech',
    authDomain: 'toranomon-civictech.firebaseapp.com',
    storageBucket: 'toranomon-civictech.firebasestorage.app',
    measurementId: 'G-BZ8QB09LNV',
  );
}
